inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
    - 'config/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*.rb'
