language: ruby
rvm:
- 2.5.3
addons:
  postgresql: '9.6'
before_install:
- openssl aes-256-cbc -K $encrypted_413ed5989022_key -iv $encrypted_413ed5989022_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- gem install bundler
- gem update --system
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
