language: ruby
rvm:
- 2.5.1
addons:
  postgresql: '9.6'
before_install:
- openssl aes-256-cbc -K $encrypted_c6e50c063231_key -iv $encrypted_c6e50c063231_iv
  -in app.yaml.enc -out app.yaml -d
- openssl aes-256-cbc -K $encrypted_413ed5989022_key -iv $encrypted_413ed5989022_iv
  -in global-math-project-fb8ec2b0dba5.json.enc -out global-math-project-fb8ec2b0dba5.json
  -d
- gem install bundler
- gem update --system
services:
- postgresql
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: global-math-project-fb8ec2b0dba5.json
  project: global-math-project-201820
  default: true
