default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/gmp_api_development

test:
  <<: *default
  database: db/gmp_api_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: <%= Rails.application.credentials[:production][:database][:password] %>
  database: gmp_api_production
  host: /cloudsql/global-math-project-201820:us-east1:gmp-api-production
