test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  credentials: <%= Rails.root.join("global-math-project-fb8ec2b0dba5.json") %>
  project: global-math-project-201820
  bucket: gmp-production-storage
